#ifndef ROBOT_PLUG_PLAY_H
#define ROBOT_PLUG_PLAY_H

#include "BOARD.h"

#ifdef ROBOT_KEYBOARD_TEST
#define ROBOT_PLUGPLAY_DEFAULT_ON 0
#else
#define ROBOT_PLUGPLAY_DEFAULT_ON 1
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BNO055)
#define ROBOT_PLUGPLAY_USE_BNO055 1
#else
#define ROBOT_PLUGPLAY_USE_BNO055 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_DRIVE_MOTORS)
#define ROBOT_PLUGPLAY_USE_DRIVE_MOTORS 1
#else
#define ROBOT_PLUGPLAY_USE_DRIVE_MOTORS 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_LAUNCHER_SERVO)
#define ROBOT_PLUGPLAY_USE_LAUNCHER_SERVO 1
#else
#define ROBOT_PLUGPLAY_USE_LAUNCHER_SERVO 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SHOOTER_MOTOR)
#define ROBOT_PLUGPLAY_USE_SHOOTER_MOTOR 1
#else
#define ROBOT_PLUGPLAY_USE_SHOOTER_MOTOR 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_STEPPER)
#define ROBOT_PLUGPLAY_USE_STEPPER 1
#else
#define ROBOT_PLUGPLAY_USE_STEPPER 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BEACON_ADC)
#define ROBOT_PLUGPLAY_USE_BEACON_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_BEACON_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SHOOTER_ADC)
#define ROBOT_PLUGPLAY_USE_SHOOTER_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SHOOTER_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_TAPE) || defined(ROBOT_HW_USE_TAPE1)
#define ROBOT_PLUGPLAY_USE_TAPE1 1
#else
#define ROBOT_PLUGPLAY_USE_TAPE1 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_TAPE) || defined(ROBOT_HW_USE_TAPE2)
#define ROBOT_PLUGPLAY_USE_TAPE2 1
#else
#define ROBOT_PLUGPLAY_USE_TAPE2 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_TAPE) || defined(ROBOT_HW_USE_TAPE3)
#define ROBOT_PLUGPLAY_USE_TAPE3 1
#else
#define ROBOT_PLUGPLAY_USE_TAPE3 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_TAPE) || defined(ROBOT_HW_USE_TAPE4)
#define ROBOT_PLUGPLAY_USE_TAPE4 1
#else
#define ROBOT_PLUGPLAY_USE_TAPE4 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_TAPE) || defined(ROBOT_HW_USE_TAPE5)
#define ROBOT_PLUGPLAY_USE_TAPE5 1
#else
#define ROBOT_PLUGPLAY_USE_TAPE5 0
#endif

#define ROBOT_PLUGPLAY_USE_ANY_TAPE (ROBOT_PLUGPLAY_USE_TAPE1 || \
    ROBOT_PLUGPLAY_USE_TAPE2 || ROBOT_PLUGPLAY_USE_TAPE3 || \
    ROBOT_PLUGPLAY_USE_TAPE4 || ROBOT_PLUGPLAY_USE_TAPE5)

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID1_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID1_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID1_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID2_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID2_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID2_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID3_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID3_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID3_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID4_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID4_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID4_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID5_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID5_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID5_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_SOLENOID_ADC) || defined(ROBOT_HW_USE_SOLENOID6_ADC)
#define ROBOT_PLUGPLAY_USE_SOLENOID6_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_SOLENOID6_ADC 0
#endif

#define ROBOT_PLUGPLAY_USE_ANY_SOLENOID_ADC (ROBOT_PLUGPLAY_USE_SOLENOID1_ADC || \
    ROBOT_PLUGPLAY_USE_SOLENOID2_ADC || ROBOT_PLUGPLAY_USE_SOLENOID3_ADC || \
    ROBOT_PLUGPLAY_USE_SOLENOID4_ADC || ROBOT_PLUGPLAY_USE_SOLENOID5_ADC || \
    ROBOT_PLUGPLAY_USE_SOLENOID6_ADC)

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BUMP_ADC) || defined(ROBOT_HW_USE_BUMP1_ADC)
#define ROBOT_PLUGPLAY_USE_BUMP1_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_BUMP1_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BUMP_ADC) || defined(ROBOT_HW_USE_BUMP2_ADC)
#define ROBOT_PLUGPLAY_USE_BUMP2_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_BUMP2_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BUMP_ADC) || defined(ROBOT_HW_USE_BUMP3_ADC)
#define ROBOT_PLUGPLAY_USE_BUMP3_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_BUMP3_ADC 0
#endif

#if ROBOT_PLUGPLAY_DEFAULT_ON || defined(ROBOT_HW_USE_BUMP_ADC) || defined(ROBOT_HW_USE_BUMP4_ADC)
#define ROBOT_PLUGPLAY_USE_BUMP4_ADC 1
#else
#define ROBOT_PLUGPLAY_USE_BUMP4_ADC 0
#endif

#define ROBOT_PLUGPLAY_USE_ANY_BUMP_ADC (ROBOT_PLUGPLAY_USE_BUMP1_ADC || \
    ROBOT_PLUGPLAY_USE_BUMP2_ADC || ROBOT_PLUGPLAY_USE_BUMP3_ADC || \
    ROBOT_PLUGPLAY_USE_BUMP4_ADC)

void RobotPlugPlay_PrintConfig(void);
uint8_t RobotPlugPlay_IsTapeEnabled(uint8_t sensorNumber);
uint8_t RobotPlugPlay_IsSolenoidADCEnabled(uint8_t sensorNumber);
uint8_t RobotPlugPlay_IsBumpADCEnabled(uint8_t sensorNumber);

#endif /* ROBOT_PLUG_PLAY_H */
